AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Capfile'
    - 'config.ru'

AsciiComments:
  Enabled: false

TrailingBlankLines:
  EnforcedStyle: final_blank_line

Documentation:
  Enabled: false

AbcSize:
  Max: 25

MethodLength:
  Max: 20

LineLength:
  Enabled: false

BlockLength:
  Exclude:
    - '**/*.rake'

FrozenStringLiteralComment:
  Enabled: false

